name: kooly_app
description: "Kooly App."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.devix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.3.0
  flutter_native_splash: 
    git:
      url: https://gitcode.com/CPF-Flutter/fluttertpc_flutter_native_splash.git

  shared_preferences:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

flutter_icons:
  image_path: "image/icon.png"
  android: true 
  ios: true

flutter_native_splash:
  color: "#42a5f5"
  image: image/icon.png